global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "scenario-runner"
    static_configs:
      - targets: ["scenario-runner:8003"]

  - job_name: "worker"
    static_configs:
      - targets: ["worker:9000"]

